twig:
    form_themes: ['bootstrap_5_layout.html.twig']

    default_path: '%kernel.project_dir%/templates'

    paths:
        'templates/admin': 'admin'

    globals:
        myname: 'Wojciech Pastuszko'
        job_dev: 'PHP Developer111'
        image: '%images_directory%'

when@test:
    twig:
        strict_variables: true
